### ISSUE TITLE
FilterImage crash on runtime: ModelEntity is not a member

### ISSUE THREAD

**Issue by phaldan** [Zeta-Project/zeta#54]
Running filter image results in a crash.
Generator output:

```
info : 21:32:25.872 [main] INFO  Main$ - Execute Filter
info : 21:32:27.999 [main] INFO  d.h.z.persistence.PersistenceModule - Mongo connection: mongodb:27017
info : 21:32:28.007 [main] INFO  reactivemongo.api.MongoDriver - No mongo-async-driver configuration found
info : 21:32:28.203 [main] INFO  reactivemongo.api.MongoDriver - [Supervisor-1] Creating connection: Connection-2
info : 21:32:28.417 [reactivemongo-akka.actor.default-dispatcher-2] INFO  r.core.actors.MongoDBSystem - [Supervisor-1/Connection-2] Starting the MongoDBSystem akka://reactivemongo/user/Connection-2
info : 21:32:28.447 [main] INFO  Main$ - Run filter: 0f23843a-8069-4d83-9fdd-ecd3366356b4
info : 21:32:29.100 [ForkJoinPool-4-worker-7] INFO  Main$ - compile filter
info : 21:32:30.392 [ForkJoinPool-4-worker-3] ERROR Main$ - scala.tools.reflect.ToolBoxError: reflective compilation has failed:

object ModelEntity is not a member of package de.htwg.zeta.common.models.entity
not found: type ModelEntity
java.lang.Exception: scala.tools.reflect.ToolBoxError: reflective compilation has failed:

object ModelEntity is not a member of package de.htwg.zeta.common.models.entity
not found: type ModelEntity
	at Main$.Main$$compileFilter(Main.scala:95)
	at Main$$anonfun$4$$anonfun$5$$anonfun$apply$2.apply(Main.scala:55)
	at Main$$anonfun$4$$anonfun$5$$anonfun$apply$2.apply(Main.scala:54)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: scala.tools.reflect.ToolBoxError: reflective compilation has failed:

object ModelEntity is not a member of package de.htwg.zeta.common.models.entity
not found: type ModelEntity
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.throwIfErrors(ToolBoxFactory.scala:316)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.wrapInPackageAndCompile(ToolBoxFactory.scala:198)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.compile(ToolBoxFactory.scala:252)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$compile$2.apply(ToolBoxFactory.scala:429)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$compile$2.apply(ToolBoxFactory.scala:422)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.liftedTree2$1(ToolBoxFactory.scala:355)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:355)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.compile(ToolBoxFactory.scala:422)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.eval(ToolBoxFactory.scala:444)
	at Main$.Main$$compileFilter(Main.scala:98)
	... 11 common frames omitted

```

**Comment by phaldan** [comment]
ModelEntity is used in the scalaFilter, basicGenerator and specificGenerator project.

https://github.com/Zeta-Project/zeta/blob/bd3c8226dcfa8b052120298f6a5c8052b4094598/api/images/filter/scala/src/main/scala/Main.scala#L83-L106

https://github.com/Zeta-Project/zeta/blob/bd3c8226dcfa8b052120298f6a5c8052b4094598/api/server/app/de/htwg/zeta/server/controller/restApi/FilterRestApi.scala#L149-L157

https://github.com/Zeta-Project/zeta/blob/bd3c8226dcfa8b052120298f6a5c8052b4094598/api/images/generator/basic/src/main/scala/de/htwg/zeta/generator/basic/Main.scala#L52-L98

https://github.com/Zeta-Project/zeta/blob/bd3c8226dcfa8b052120298f6a5c8052b4094598/api/images/generator/specific/src/main/scala/de/htwg/zeta/generator/specific/Main.scala#L81-L126
